sonar.projectKey=tp4-devops-app
sonar.projectName=TP4 DevOps App
sonar.sources=app
sonar.tests=app/tests
sonar.test.inclusions=app/tests/**
sonar.exclusions=app/tests/**
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info
